export const USER_MOVIES_FETCH_REQUESTED = 'USER_MOVIES_FETCH_REQUESTED';
export const USER_MOVIES_FETCH_SUCCEDED = 'USER_MOVIES_FETCH_SUCCEDED';
export const USER_MOVIES_FETCH_FAILED = 'USER_MOVIES_FETCH_FAILED';